/*
 * defines.h
 *
 *  Created on: Oct 10, 2022
 *      Author: mub91
 */

#ifndef DEFINES_H_
#define DEFINES_H_


#define ROWS 4
#define COLUMNS 5
#define LED_MATRIX_SIZE 32
#define LED_MATRIX_ROWS 26
#define LED_MATRIX_COLUMNS 32
#define JOYSTICK_V ADC_MEM0
#define JOYSTICK_H ADC_MEM1
#define JOYSTICK_V_PORT P5
#define JOYSTICK_V_PIN  5
#define JOYSTICK_H_PORT P5
#define JOYSTICK_H_PIN 4
#define PUSH_INPUT P1->IN
#define PUSH_PIN 0x10
#define PLAYER1_PUSH_PIN 0x20
#define ADC14_CONVERSION_START ADC14->CTL0|=1
#define ADC14_CONVERSION_FINISHED ADC14->IFGR0
#define ENCODER1_A_INTERRUPT P3->IFG & BIT5
#define ENCODER1_B_INTERRUPT P3->IFG & BIT6

#define ENCODER1_A_HIGH P3->IN & BIT5
#define ENCODER1_B_HIGH P3->IN & BIT6
#define ENCODER1_B_LOW !(P3->IN & BIT5)

#define JOYSTICK_NEUTRAL ADC14->MEM[0] > 11000 && ADC14->MEM[1] > 11000
#define JOYSTICK_UP ADC14->MEM[0] < 5000
#define JOYSTICK_DOWN ADC14->MEM[0] > 14000
#define JOYSTICK_LEFT ADC14->MEM[1] < 5000
#define JOYSTICK_RIGHT ADC14->MEM[1] > 13000

#define ADC14_CONVERSION_START_ADDR(REG)    (uint32_t)((REG<<ADC14_CTL1_CSTARTADD_OFS) & ADC14_CTL1_CSTARTADD_MASK)

#define SELECT_A       P1 -> OUT |= GPIO_PIN5;
#define SELECT_B       P4 -> OUT |= GPIO_PIN2;
#define SELECT_C       P4 -> OUT |= GPIO_PIN7;
#define SELECT_D       P4 -> OUT |= GPIO_PIN4;
#endif /* DEFINES_H_ */
//end of file
